config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  resources :students do
    resources :student_course_records do
      post :bulk_update_order, on: :collection
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id           :bigint           not null, primary key
#  course_name  :string
#  credits      :integer
#  college_name :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Course < ApplicationRecord

  has_many :student_course_records, dependent: :destroy
  broadcasts_to -> (course) { :courses }
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string
#  article    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  broadcasts_to -> (post) { :posts }
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id         :bigint           not null, primary key
#  name       :string
#  age        :integer
#  sex        :integer
#  married    :boolean
#  address    :string
#  city       :string
#  state      :string
#  zip        :string
#  phone      :integer
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Student < ApplicationRecord

  enum_for :married, { single: 1, married: 2 }
  enum_for :sex, { male: 1, female: 2 }

  has_many :student_course_records, dependent: :destroy
end

app/models/student_course_record.rb
# == Schema Information
#
# Table name: student_course_records
#
#  id            :bigint           not null, primary key
#  student_id    :integer
#  start_date    :date
#  end_date      :date
#  registered_at :date
#  score         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  course_id     :integer
#  order         :integer
#
class StudentCourseRecord < ApplicationRecord

  belongs_to :student
  belongs_to :course
  broadcasts_to -> (student_course_record) { :student_course_records }, inserts_by: :prepend
  broadcasts_refreshes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/student_course_records_controller.rb
class StudentCourseRecordsController < ApplicationController
  include StudentCourseRecordHelper
  include ActionView::RecordIdentifier

  def index
    @student = Student.find(params[:student_id])
    @student_course_records = StudentCourseRecord.where(student_id: @student.id).includes(:course).order(:order)
    @courses = Course.where.not(id: @student_course_records.pluck(:course_id))
  end

  def new
    @student = Student.find(params[:student_id])
    @student_course_record = StudentCourseRecord.new
  end

  def bulk_update_order
    @student = Student.find(params[:student_id])
    checked_items = check_order_params(JSON.parse(params["order_array"]))

    updated_records = checked_items.map do |item|
      student_course_record = StudentCourseRecord.find(item["id"])
      student_course_record.update(order: item["order"])
      student_course_record
    end

    # Render turbo stream for each updated student_course_record
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: updated_records.map { |record|
          turbo_stream.replace(
            record,
            partial: "student_course_records/student_course_record",
            locals: { student_course_record: record, student: @student }
          )
        }.join.html_safe
      end
    end
  end

  def show
    @student = Student.find(params[:student_id])
    @student_course_record = StudentCourseRecord.find(params[:id])
  end

  def create
    @student = Student.find(params[:student_id])
    @student_course_record = StudentCourseRecord.new(student_course_record_params)

    respond_to do |format|
      format.html do
        begin
          @student_course_record.save!
          redirect_to student_student_course_records_path(@student)
        rescue
          render :new
        end
      end
      format.json do
        if @student_course_record.save
          render json: { status: :created, data: { student_course_record_id: @student_course_record.id }}
        else
          render json: @student_course_record.errors, status: :unprocessable_entity
        end
      end
      # May use this in the future to render the partial for a new student course record
      # format.turbo_stream do
      #   if @student_course_record.save
      #     render turbo_stream: turbo_stream.replace(
      #       dom_id(@student_course_record),
      #       partial: "student_course_records/student_course_record",
      #       locals: { student_course_record: @student_course_record, student: @student }
      #     )
      #   else
      #     head :internal_server_error
      #   end
      # end
    end
  end

  def edit
    @student = Student.find(params[:student_id])
    @student_course_record = StudentCourseRecord.find(params[:id])
  end

  def update
    @student = Student.find(params[:student_id])
    @student_course_record = StudentCourseRecord.find(params[:id])
    begin
      @student_course_record.update!(student_course_record_params)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@student_course_record, partial: "student_course_records/student_course_record", locals: { student_course_record: @student_course_record, student: @student }) }
        format.html { redirect_to student_student_course_records_path(@student) }
      end
    rescue
      render :edit
    end
  end

  def destroy
    @student_course_record = StudentCourseRecord.find(params[:id])
    @student_course_record.destroy
    respond_to do |format|
      format.html { redirect_to student_student_course_records_path(@student) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@student_course_record) }
    end
  end

  private

  def student_course_record_params
    params.require(:student_course_record)
          .permit(:student_id, :order, :course_id, :name,
                  :score, :start_date, :end_date, :registered_at)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    begin
      @student = Student.create!(student_params)
      redirect_to students_path
    rescue
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    begin
      @student = Student.update!(student_params)
      redirect_to students_path
    rescue
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :age, :sex, :married, :address, :city, :state, :zip, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/student_course_record_helper.rb
module StudentCourseRecordHelper


  def check_order_params(params)
    new_array = []
    params.each do |object|
      puts object
      new_array.push object unless contains_non_integer?(object["id"])
    end

    new_array
  end

  def contains_non_integer?(str)
    Integer(str)
    false
  rescue ArgumentError
    true
  end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/courses/_course.html.erb
<%= turbo_frame_tag dom_id(course), 'data-course-id': course.id do %>
  <div class="bg-white rounded-lg shadow-md p-2 mt-5">
    <div class="flex flex-row justify-between">
      <div class="w-3/8 p-2">
        <strong>Name</strong>
        <p class="text-gray-900"><%= course.course_name %></p>
      </div>
      <div class="w-3/8 p-2">
        <strong>Credits</strong>
        <p class="text-gray-700"><%= course.credits %></p>
      </div>
      <div class="w-3/8 p-2">
        <strong>College</strong>
        <p class="text-gray-700"><%= course.college_name %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= content_for :head %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do%>
  <div class="border flex-col mt-2">
    <strong><%= post.title%></strong>
    <%= post.article %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Posts #index</h1>
  <p>Find me in app/views/posts/index.html.erb</p>
  <%= turbo_stream_from :posts %>
  <div id="posts">
    <%= render @posts %>
  </div>
</div>

app/views/student_course_records/_student_course_record.html.erb
<%= turbo_frame_tag dom_id(student_course_record), action: 'replace', 'data-id': student_course_record.id do %>
  <div class="bg-white rounded-lg shadow-md p-2 mb-5">
    <div class="flex flex-row justify-between">
      <div class="w-5/8 p-2">
        <strong>Order</strong>
        <p class="text-gray-900"><%= student_course_record.order %></p>
      </div>
      <div class="w-5/8 p-2">
        <strong>Name</strong>
        <p class="text-gray-900"><%= student_course_record.course.course_name %></p>
      </div>
      <div class="w-1/8 p-2">
        <%= turbo_frame_tag "edit_score_#{student_course_record.id}" do %>
          <%= form_with model: [@student, student_course_record], method: :patch, remote: true do |f| %>
            <strong>Score</strong>
            <%= f.text_field :score, class: "text-grey-900" %>
            <%= f.submit 'Update' %>
          <% end %>
        <% end %>
        <strong>Score</strong>
        <p class="text-gray-700"><%= student_course_record.score %></p>
      </div>
      <div class="w-1/8 p-2">
        <strong>Credits</strong>
        <p class="text-gray-700"><%= student_course_record.course.credits %></p>
      </div>
      <div class="w-3/8 p-2">
        <%= turbo_frame_tag "edit_start_date_#{student_course_record.id}" do %>
          <%= form_with model: [@student, student_course_record], method: :patch, remote: true do |f| %>
            <strong>Start date</strong>
            <%= f.text_field :start_date, class: "text-grey-900" %>
            <%= f.submit 'Update' %>
          <% end %>
        <% end %>
        <strong>Start date</strong>
        <p class="text-gray-700"><%= student_course_record.start_date %></p>
      </div>
      <div class="w-3/8 p-2">
        <%= turbo_frame_tag "edit_end_date_#{student_course_record.id}" do %>
          <%= form_with model: [@student, student_course_record], method: :patch, remote: true do |f| %>
            <strong>End date</strong>
            <%= f.text_field :end_date, class: "text-grey-900" %>
            <%= f.submit 'Update' %>
          <% end %>
        <% end %>
        <strong>End date</strong>
        <p class="text-gray-700"><%= student_course_record.end_date %></p>
      </div>
      <div class="w-3/8 p-2">
        <strong>Registered at</strong>
        <p class="text-gray-700"><%= student_course_record.registered_at %></p>
      </div>
      <div class="w-3/8 p-2">
        <%= button_to "Delete",
          student_student_course_record_path(@student, student_course_record),
          action: 'delete', method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
<% end %>

app/views/student_course_records/index.html.erb
<div>
  <h1 class="mb-30">The Student Course Records for <%= @student.name %></h1>
  </br>
  <button onclick="togglePanel()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-5">Add Course</button>
  </br>
  <% turbo_stream_from @student_course_records %>
  <div id="student_course_records" data-controller="student-course-records">
    <%= render @student_course_records %>
  </div>
  <% turbo_stream_from :courses %>
  <div id="course_panel" style="display: none; position: fixed; right: 0; top: 0; width: 500px; height: 100%; overflow: auto; background-color: #f1f1f1; margin: 0px 5px; padding: 15px;">
    <h1 style="font-size: 30px"> Courses </h1>
    <div id="courses" data-controller="courses">
      <%= render @courses %>
    </div>
  </div>
</div>

<script>
  function togglePanel() {
    var panel = document.getElementById('course_panel');
    if (panel.style.display === "none") {
      panel.style.display = "block";
    } else {
      panel.style.display = "none";
    }
  }
</script>

app/views/students/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student Index</title>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss/dist/tailwind.min.css">
  </head>
  <body>
    <div class="container mx-auto">
      <h1 class="text-3xl font-bold mb-8">Student Index</h1>
      <div class="grid grid-cols-3 gap-4 mt-8">
        <% @students.each do |student| %>
          <%= turbo_frame_tag dom_id(student) do %>
            <%= link_to student_path(student) do %>
              <div class="bg-white rounded-lg shadow-md p-4">
                <h2 class="text-xl font-bold mb-4"><%= student.name %></h2>
                <p class="text-gray-700"><%= student.age %></p>
              </div>
            <% end %>
          <% end%>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/students/show.html.erb
<div class="flex flex-col items-center justify-center min-h-screen bg-gray-100" j >
  <div class="max-w-lg w-full bg-white shadow-md rounded-md overflow-hidden">
    <div class="bg-gray-200 px-4 py-2">
      <h1 class="text-lg font-bold text-gray-800">Student Information for
        <%= @student.name %>
      </h1>
    </div>
    <div class="px-4 py-2">
      <p class="text-gray-700 font-medium">Name: <%= @student.name %></p>
      <p class="text-gray-700 font-medium">Email: <%= @student.email %></p>
      <p class="text-gray-700 font-medium">Age: <%= @student.age %></p>
      <p class="text-gray-700 font-medium">Address: <%= @student.address + ', ' + @student.city + ', ' + @student.state + ' ' + @student.zip %></p>
    </div>
    <div class="button">
      <%= button_to 'View Student Course Records', student_student_course_records_path(@student), method: :get %>
    </div>
  </div>
</div>